title: Networking Conference Deadlines # (Maintained by @albertgranalcoz)
# email: galberto@ethz.ch
description: Countdowns to top Networking conference deadlines
author: Albert Gran Alcoz

domain: "netdeadlines.com/netdeadlines/"
baseurl: "/netdeadlines"

twitter_username: albertgran
twitter_hashtag: machinelearning
github_username: albertgranalcoz
github_repo: netdeadlines

markdown: kramdown

include: ['_pages']