title: Networking Conference Deadlines # (Maintained by @albertgranalcoz)
# email: galberto@ethz.ch
description: Countdowns to top Networking conference deadlines
author: Albert Gran Alcoz

domain: "justpapers.herokuapp.com"
baseurl: ""

twitter_username: albertgran
twitter_hashtag: machinelearning
github_username: albertgranalcoz
github_repo: net-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']