title: Networking Conference Deadlines # (Maintained by @albertgranalcoz)
# email: galberto@ethz.ch
description: Countdowns to top Networking conference deadlines
author: Albert Gran Alcoz

domain: "https://albertgranalcoz.github.io/net-deadlines/"
baseurl: "/net-deadlines"

twitter_username: albertgran
twitter_hashtag: machinelearning
github_username: albertgranalcoz
github_repo: net-deadlines

markdown: kramdown

include: ['_pages']